"""
Project Euler Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import sys
sys.path.append("..")
# We gotta reuse code guyz
from maths import fib

def fib_even_sum():
    curr_sum = 0
    fib_list = fib.fib(4000000)
    for n in fib_list:
        if n % 2 == 0:
            curr_sum += n
    return curr_sum

print(fib_even_sum())
